<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- Suppress obsolete-API warnings in pymavlink generated code -->
    <NoWarn>$(NoWarn);SYSLIB0021</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="MAVLink\**\*.cs">
      <AutoGen>true</AutoGen>
    </Compile>
  </ItemGroup>
</Project>
